const { model, Schema } = require("mongoose");

const applicationSchema = new Schema({
  userId: String,
  name: String,
  surname: String,
  email: String,
  gender: String,
  address: String,
  phoneNumber: Number,
  postalCode: String,
  municipality: String,
  municipalAccountNumber: String,
  idNumber: String,
  race: String,
  country: String,
  houseHoldHead: Boolean,
  maritalStatus: String,
  spauseIdNumber: String,
  spauseName: String,
  spauseSurname: String,
  dependents: Boolean,
  idBook: String,
  bankStatement: String,
  affidavid: String,
  companyName: String,
  companyEmail: String,
  companyPhoneNumber: Number,
  companyType: String,
  regNumber: String,
  companyDepartment: String,
  income: String,
  sourceOfIncome: String,
  sassaNumber: String,
  standType: String,
  wardNumber: String,
  suburb: String,
  applciantIdNumber: String,
  applicantName: String,
  applicantSurname: String,
  applicantPhoneNumber: Number,
  relationship: String,
  spauseIdNumber: String,
  spauseName: String,
  spauseSurname: String,
  ageRange: String,
  reason: String,
  status: String,
  applicationDate: String,
  deceased: String,
  createdAt: String,
});

module.exports = model("Application", applicationSchema);
